name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONFIG: /tmp/.docker

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          creadential_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGION }}-docker.pkg.dev

      - name: Log
        run: |
          echo ${{  secrets.GCP_ARTIFACT_REGION}}

      - name: Push Docker image
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGION }}-docker.pkg.dev
          docker build -t ${{ secrets.GCP_ARTIFACT_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/${{ secrets.IMAGE_NAME }}:latest .
          docker push ${{ secrets.GCP_ARTIFACT_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/${{ secrets.IMAGE_NAME }}:latest
